trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  org: org
  project: project
  PAT: $(PAT_TOKEN)

steps:

- checkout: self
  persistCredentials: true

- script: |

    git config --global user.email "pipeline@ado.com"
    git config --global user.name "ADO Pipeline"

    repo1=https://$(PAT)@dev.azure.com/$(org)/$(project)/_git/repo1
    repo2=https://$(PAT)@dev.azure.com/$(org)/$(project)/_git/repo2
    repo3=https://$(PAT)@dev.azure.com/$(org)/$(project)/_git/repo3

    git remote add repo1 $repo1
    git remote add repo2 $repo2
    git remote add repo3 $repo3

    git push repo1 HEAD:main
    git push repo2 HEAD:main
    git push repo3 HEAD:main

  displayName: Push Code to Multiple Repos
